### ISSUE TITLE
missleading README.md information

### ISSUE THREAD

**Issue by jurnix** [Goddard-Fortran-Ecosystem/pFUnit#104]
After following the README guide, I have experienced the following error:
```
./testSuites.inc(1): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % (
ADD_TESTS_SUITE(helloWorld_suite)
---------------------------------^
./testSuites.inc(1): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % (
ADD_TESTS_SUITE(helloWorld_suite)
---------------------------------^
./testSuites.inc(1): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % (
ADD_TESTS_SUITE(helloWorld_suite)
---------------------------------^
compilation aborted for /linkhome/rech/lmd/rlmd998/own_libs/pffunit-serial/include/driver.F90 (code 1)
make: *** [tests.x] Error 1

```
It turns out the README.md tells you to add testSuites.inc with the following content:

> ! Add a test suite to the build.
> ADD_TESTS_SUITE(helloWorld_suite)

But there is a problem, because there is an extra S, from TESTS to TEST. After applying this simple modification it successfully compiles:

> ! Add a test suite to the build.
> ADD_TEST_SUITE(helloWorld_suite)

It took me a few days to realize about it.

**Comment by tclune** [comment]
Very sorry about that.   Will fix immediately!
