### ISSUE TITLE
*.pf synthax highlighting on GitHub

### ISSUE THREAD

**Issue by Libavius** [Goddard-Fortran-Ecosystem/pFUnit#111]
You could add the file ``.gitattributes`` to the main directory that contains the following line:
```
*.pf linguist-language=fortran
```
That way, the *.pf files have fortran synthax highlighting on github.
This is already done for your pFUnit_demos repo: https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos/blob/master/.gitattributes

Thanks for the great unit testing environment!

**Comment by tclune** [comment]
Thank you for the suggestion and apologies for somehow missing this ticket when it was open.   I just discovered the linguist-language feature a couple weeks earlier, but only pushed it to the demo repository.    I'll add it on the release branch now (which should become the master very very soon)
