### ISSUE TITLE
CMake error in the logic in include/add_pfunit_sources.cmake or callers

### ISSUE THREAD

**Issue by zbeekman** [Goddard-Fortran-Ecosystem/pFUnit#118]
Hi @tclune et al.,

There seems to be a logic error somewhere in either `include/add_pfunit_sources.cmake` or one of the functions calling this:

```
CMake Error at include/add_pfunit_sources.cmake:33 (file):
  file problem creating directory:
  /tmp.F90unit-20190507-36706-1qjb902/pFUnit-4.0.0/build/tests/funit-core
Call Stack (most recent call first):
  include/add_pfunit_ctest.cmake:47 (add_pfunit_sources)
  tests/funit-core/CMakeLists.txt:98 (add_pfunit_ctest)
```

Your code is taking the current working directory and substituting `.F90` in the directory path. e.g., 

`/tmp/pfunit-20190507-36706-1qjb902/pFUnit-4.0.0/build` ➡️ `/tmp/pfunit-20190507-36706-1qjb902/pFUnit-4.0.0/build`

I think I know the fix for this and can open a PR. This is a blocker for adding a homebrew formula, so the sooner a minor release can be minted after fixing, the better.

**Comment by tclune** [comment]
Hmm.  I wonder why this does not affect my own build (or those in travis).   Happy to look at a PR.

**Comment by zbeekman** [comment]
IDK, but you def should not be passing a file extension including the period to `string( REGEX REPLACE ${file_ext} ...` 😉 

To trigger this the build directory or a parent must start with `pf` so that `/pf` gets substituted with `.F90`. Furthermore, if the parent of the parent is writeable by you, the user, then you may never notice the bug: CMake may happily create the equivalent of `/tmp.F90unit...` in my case, but if it's in your home directory or something e.g., `~/codes/pfunit/build` ➡️ `~/codes.F90unit/build` you might just not notice it? 🤷‍♂ 

Now that I'm past that issue I'm seeing test failures when I run `make test` after I run `make install`. I'm not sure if these are normal/expected and if I might need to do something special when I invoke CMake to prevent this.

I have [a gist](https://gist.github.com/zbeekman/74733db18d8d1e7ccd8e25e54543119c) including:
1. The [CMakeCache.txt](https://gist.github.com/zbeekman/74733db18d8d1e7ccd8e25e54543119c#file-cmakecache-txt)
2. The [output of `make test`](https://gist.github.com/zbeekman/74733db18d8d1e7ccd8e25e54543119c#file-make-test-log)
3. The [Homebrew formula](https://gist.github.com/zbeekman/74733db18d8d1e7ccd8e25e54543119c#file-pfunit-rb) I am cooking up (but needs a `test do` block, and environment/CMake args may need tweaking)

The configure line looks like:

```
cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/pfunit/4.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
```

These are basically a bunch of defaults passed by homebrew.

I'll poke around a bit more to try to figure this out. I'm running in the interactive homebrew build environment so the environment is heavily sanitized. It's possible that I need missing python modules, or that OpenMPI is balking at oversubscription and/or that I need to tweak my configure line.
