### ISSUE TITLE
CMake command containing spaces collapses to a single string

### ISSUE THREAD

**Issue by rafmudaf** [Goddard-Fortran-Ecosystem/pFUnit#12]
On NREL's Peregrine compute system, which runs CentOS 7 and cmake 3.8, this cmake command found at `source/CMakeLists.txt` line 11 collapses to a single string:
```
COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/GenerateAssertsOnArrays.py --maxRank ${MAX_RANK}
```

The fix is to wrap the argument in quotes:
```
COMMAND "${PYTHON_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/GenerateAssertsOnArrays.py" "--maxRank" "${MAX_RANK}"
```

I see that the CMake configuration has changed in the `develop` branch. I'll test that branch on our system and issue a pull request with our cmake fixes, if necessary.

**Comment by tclune** [comment]
The develop branch is a substantial redesign that I'm targeting for pfunit 4.0.     While it is functioning and is (mostly) backward compatible, I don't think it is really ready for external use.    At the very least, the "install" step is currently broken.    

I do hope to fix the issue you mentioned above on master as well as the "install" step on develop today.

**Comment by tclune** [comment]
@rafmudaf  I am going to commit the change, but am curious if you have similar issues in the tests/CMakefile.  E.g., the line below would also possibly need quotes?

    add_custom_target(tests COMMAND ${MPIEXEC} ${MPIEXEC_NUMPROC_FLAG} 4 ${MPIEXEC_PREFLAGS} tests/${TEST_EXE} DEPENDS ${TEST_EXE} WORKING_DIRECTORY ${CMAKE_BINARY_DIR})

Maybe the leading dashes in  the --maxrank flag cause problems in the former?
