### ISSUE TITLE
README-INSTALL inconsistent with build: no Makefile

### ISSUE THREAD

**Issue by brhillman** [Goddard-Fortran-Ecosystem/pFUnit#121]
It looks like support for building with GNU make has been removed, but the documentation in the READMEs (especially the main README.md documentation) still refers to the make build using GNUMakefile, which no longer exists.

**Comment by tclune** [comment]
Yes - I am very sorry that the documentation is currently inconsistent.    My day job has been keeping me very busy, and documentation is joyless at the best of times.

I'll try to make a quick pass right now and at least update the truly broken aspects.

**Comment by brhillman** [comment]
No problem, just wanted to point it out. Thanks for the quick response!
