### ISSUE TITLE
gfortran 5.4.0 - "Error: Assignment to an allocatable polymorphic variable at (1) is not yet supported"

### ISSUE THREAD

**Issue by donaldjmorton** [Goddard-Fortran-Ecosystem/pFUnit#123]
This is my first time trying the software.  I'm trying to build with gfortran v5.4.0 per README instructions.

```
$ git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
$ export FC=gfortran
$ mkdir build; cd build
$ cmake ..
.
.
.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/morton/tmp/pFUnit/build
```
Then, when I try to build the tests I get numerous "allocatable polymorphic variables..." errors that prevent me from going further...

```
$ make tests
.
.
.
/home/morton/tmp/pFUnit/extern/fArgParse/src/BaseAction.F90:309:6:

       n_arguments = this%n_arguments
      1
Error: Assignment to an allocatable polymorphic variable at (1) is not yet supported
.
.
.
```

Have looked far and wide for what this even means and am wondering if there's a simple fix or not.

**Comment by tclune** [comment]
@donaldjmorton    The compiler is giving a correct message.   That version of gfortran did not support the F2008 feature that allows automatic allocation of polymorphic entities on assignment.    This is not crucial for pFUnit's design, but it allows a cleaner style of coding. 

If this is crucial, it would probably not be hard to create a branch that uses the older F2003 syntax with explicit allocation.    But I suspect there would still be other issues with gfortran 5.x.  There are somewhat similar issues with automatic allocation of strings that, although part of the F2003 standard, were generally buggy in most compilers until somewhat recently.

Hopefully you can upgrade compilers?    Note that you can still use an older compiler for your actual application - just building it separately when it is under test.   Not ideal.

The other alternative is to stick with pFUnit 3.x.    4.0 mostly was about cleaning up the implementation to enable introduction of new features.   At the moment, there are relatively few actual new features in 4.0.

Please let me know how you decide to proceed.

**Comment by donaldjmorton** [comment]
@tclune Thank you very much for your reply.  I've been tasked with trying to create unit tests with mocking for an old legacy code (but one that still evolves), FLEXPART, that's used operationally, so I'm exploring options.  From what I've found, pFUnit seems to be recent and, wow, there's actually a lot of documentation.

In the short term I think I'll try to work with pFUnit 3.x just to gain some understanding of what I'm doing and what might be possible.  The system this runs on tends to be kind of antiquated and frozen (gfortran 4.8, I believe).

**Comment by tclune** [comment]
Note that the documentation is, er, a bit dated.    But other than the install step, they should be spot on for the last pFUnit 3 version.       I should take some time to do a full overhaul of the documentation, but this is unlikely.   If you do end up using pFUnit 4, I recommend looking at the [demos](https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos).    

gfortran 4.8.3 should work with pFUnit 3.   If some of the minor tweaks of the last few years has broken that backward compatibility, just let me know and I'l see if a patch can be made.
