### ISSUE TITLE
Problems installing on OSX 10.14.5

### ISSUE THREAD

**Issue by jmorris-uk** [Goddard-Fortran-Ecosystem/pFUnit#124]
Hi,

I'm having issues trying to install pFUnit on OSX Mojave 10.14.5. Below are the steps that I have taken, hopefully you can see where I'm going wrong.

1. clone the repository
2. `mkdir build`
3. `cd build`
4. `cmake .. -DSKIP_MPI -DSKIP_OPENMP` (terminal output in attached output_1.log)
5. `make tests` (terminal output in attached output_2.log)
6. `make install` (terminal output in attached output_3.log plus errors in screenshot below about "libfunit.a" and "no symbols")

In the folder installed/PFUNIT-4.0/include I have the files listed in the attached screenshot below but no base.mk. 

<img width="1242" alt="env" src="https://user-images.githubusercontent.com/46964268/60191515-5d21f400-982c-11e9-9598-4bfb1e347496.png">
<img width="1242" alt="installed_include_folder" src="https://user-images.githubusercontent.com/46964268/60191517-5dba8a80-982c-11e9-96b9-bd25fe35aa46.png">
<img width="1242" alt="make_install_warnings" src="https://user-images.githubusercontent.com/46964268/60191518-5dba8a80-982c-11e9-96c6-a9c4687b8a0d.png">
<img width="1242" alt="versions" src="https://user-images.githubusercontent.com/46964268/60191520-5e532100-982c-11e9-978a-c9955740ac08.png">
[output_1.txt](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/files/3330734/output_1.txt)
[output_2.txt](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/files/3330735/output_2.txt)
[output_3.txt](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/files/3330736/output_3.txt)

**Comment by tclune** [comment]
My pologies.    The latest support for pFUnit dropped support for vanilla make builds.    I did not mean to inflict this decision on projects that use pFUnit.  

The important bits that pFUnit should provide are the paths for the includes and libraries and such.     I'm a bit surprised that this layer (in the older releases) does not even have a rule for preprocessing the .pf files into .F90 files.

I'll take a stab at this over the weekend.

**Comment by tclune** [comment]
@jmorris-uk   OK - the basic problem is that the old "base.mk" is named "PFUNIT.mk" under the new release.   My apologies for not having immediately realized this. 

But while there, I noticed that I had not properly included MPI support, so fixed that up as part of this ticket.        I will also shortly update the demos in  https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos  which may help you adapt legacy builds to use the newer .mk file.

Please contact me if you have further issues.
