### ISSUE TITLE
Missing documented requirement m4

### ISSUE THREAD

**Issue by sbland** [Goddard-Fortran-Ecosystem/pFUnit#187]
```
$ make tests 

Scanning dependencies of target posix_predefined.x
[  0%] Building C object src/funit/core/CMakeFiles/posix_predefined.x.dir/posix_predefined.c.o
[  0%] Linking C executable posix_predefined.x
[  0%] Built target posix_predefined.x
Scanning dependencies of target generate_posix_parameters
[  0%] Generating posix_predefined.inc
[  0%] Built target generate_posix_parameters
Scanning dependencies of target generate-template-incs
[  0%] Generating type_template_macros.inc
/bin/sh: 1: m4: not found
extern/gFTL/include/templates/CMakeFiles/generate-template-incs.dir/build.make:77: recipe for target 'extern/gFTL/include/templates/type_template_macros.inc' failed
make[3]: *** [extern/gFTL/include/templates/type_template_macros.inc] Error 127
make[3]: *** Deleting file 'extern/gFTL/include/templates/type_template_macros.inc'
CMakeFiles/Makefile2:625: recipe for target 'extern/gFTL/include/templates/CMakeFiles/generate-template-incs.dir/all' failed
make[2]: *** [extern/gFTL/include/templates/CMakeFiles/generate-template-incs.dir/all] Error 2
CMakeFiles/Makefile2:577: recipe for target 'CMakeFiles/tests.dir/rule' failed
make[1]: *** [CMakeFiles/tests.dir/rule] Error 2
Makefile:197: recipe for target 'tests' failed
make: *** [tests] Error 2
```

Fixed by installing m4 `sudo apt install m4`

**Comment by tclune** [comment]
@sbland   There's not much I can do inside pFUnit to address this other than additional documentation.     

Let me know if the ticket can be closed.

**Comment by ChinouneMehdi** [comment]
@tclune You can use cmake function "[find_program()](https://cmake.org/cmake/help/latest/command/find_program.html)"

**Comment by sbland** [comment]
@tclune adding to docs is fine by me

**Comment by tclune** [comment]
@ChinouneMehdi -- I'm not opposed to adding find_program() for this,  and it would certainly be nice for the user to get the message early rather than late.     I am a bit wary of getting the details for find_program() correct for all systems (esp. Windows).

If someone wants to do a PR along these lines with a claim that it works on Windows, I'll test on my systems and happily make the change.

**Comment by ChinouneMehdi** [comment]
@tclune I have made a PR in Goddard-Fortran-Ecosystem/gFTL#93.
Tested on Ubuntu 18.04 and MSYS2/MinGW-w64.
