### ISSUE TITLE
BLD: XLF support for v3.2.9

### ISSUE THREAD

**Issue by tylerjereddy** [Goddard-Fortran-Ecosystem/pFUnit#192]
I've opened a PR to `spack` to add support for building with a recent XL compiler/spectrum-mpi toolchain: https://github.com/spack/spack/pull/15699

I did not open the PR directly here because I'm not familiar with backport policy here, of if you'd even want a fix for a version that old.

The code seems sufficiently different in newer versions that this specific issue is not likely to persist, though I only checked that briefly (I think `spack` has other problems with `4.0`+ though, as noted in the `package.py` there).

**Comment by tclune** [comment]
Yes - a fix that old is not likely to be relevant, but I would  certainly be interested in a PR that allows the latest version to compile under XLF.      I currently have no access to that compiler.

I also do not (yet) use spack, but I very much intend to support spack.   If you or others can identify changes that can be made in pFUnit 4 to enable/encourage use of spack, I would be very appreciative.
