### ISSUE TITLE
Command line arguments don't work with MPI driver

### ISSUE THREAD

**Issue by ZedThree** [Goddard-Fortran-Ecosystem/pFUnit#195]
The serial version works fine, but when built with MPI, the command line arguments stop working. Replicated using the serial/MPI tests in the demos repo.

**Comment by tclune** [comment]
Could you provide a few more details?  Compiler & OS and precisely what you do on the command line that is failing.   I'm fairly certain I do this regularly and need to see what might be different about your usage.

**Comment by ZedThree** [comment]
Sure thing. I'm using Fedora 31, gfortran 9.2.1, OpenMPI 4.0.2, cmake 3.16.4 and pFUnit master (cf382234).

Then build pFUnit:

```
PFUNIT_DIR=$(pwd)/build_mvce/install
cmake . -B build_mvce -DCMAKE_INSTALL_PREFIX=$PFUNIT_DIR -DSKIP_OPENMP=YES -DMPI=ON
cmake --build build_mvce --target install
```
and then the demos:
```
cmake . -B build_mvce -DCMAKE_PREFIX_PATH=$PFUNIT_DIR 
cmake --build build_mvce
```
(or equivalently the supplied `build_with_cmake_and_run.x` scripts)

Running the `Basic` `my_tests --help` gives the expected help message, but the `MPI` `mpi_tests` just runs the tests.

We're actually trying to use `--output`, but the problem exists for all the flags.

**Comment by ZedThree** [comment]
Amazing, thank you very much for fixing this!
