### ISSUE TITLE
Hamcrest still used even with SKIP_FHAMCREST

### ISSUE THREAD

**Issue by ZedThree** [Goddard-Fortran-Ecosystem/pFUnit#196]
Configure and build like:
```
$ cmake . -B build  -DSKIP_FHAMCREST=YES
$ cmake --build build
```
results in error:
```
[ 85%] Building Fortran object src/funit/CMakeFiles/funit-main.dir/FUnit.F90.o
/home/peter/Codes/gyrokinetics/pFUnit/src/funit/FUnit.F90:5:7:

    5 |    use fHamcrest
      |       1
Fatal Error: Cannot open module file ‘fhamcrest.mod’ for reading at (1): No such file or directory
compilation terminated.
```

https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/cf382234c4c13c06380d5d969c729801ca6c1c35/src/funit/FUnit.F90#L5

I think this needs to be `#ifdef`'d out or something when not using hamcrest.

**Comment by tclune** [comment]
Sorry about that.   I should be abele to patch this weekend.

**Comment by ZedThree** [comment]
No worries! Trying to use `--coverage` crashes the compiler on `use pfunit` in our code, so I'm trying to rule things out.

**Comment by tclune** [comment]
Release v4.1.7 includes this fix.
