### ISSUE TITLE
integer assert with message won't compile

### ISSUE THREAD

**Issue by cferenba** [Goddard-Fortran-Ecosystem/pFUnit#197]
I'm migrating to pFUnit 4 and have found that a few of the assertions I wrote under pFUnit 3 no longer compile.  Specifically:

```fortran
﻿   @test
   subroutine test_assert_equal()
      integer, parameter :: i_expected = 24 ! 4!
      integer, parameter :: i_greater = 99
      real, parameter :: x_expected = 9. ! 3**2
      real, parameter :: x_greater = 99. ! 3**2
      
      @assertEqual(i_expected, factorial(4))
      @assertEqual(i_expected, factorial(4), "equal-int")
      @assertGreaterThan(i_greater, factorial(4))
      ! this one won't compile!
      ! @assertGreaterThan(i_greater, factorial(4), "greater-int")
      @assertEqual(x_expected, square(3.))
      @assertEqual(x_expected, square(3.), "equal-real")
      @assertGreaterThan(x_greater, square(3.))
      @assertGreaterThan(x_greater, square(3.), "greater-real")

   end subroutine test_assert_equal
```

The other asserts compile and run as expected, but the integer assertGreaterThan with a message fails with this error:
```
/yellow/usr/projects/eap/users/cferenba/pFUnit/pFUnit-demos/Basic/tests/test_simple.pf(32): error #6285: There is no matching specific subroutine for this generic subroutine call.   [ASSERTGREATERTHAN]
  call assertGreaterThan(i_greater, factorial(4), "greater-int", &
-------^
compilation aborted for test_simple.F90 (code 1)
gmake[1]: *** [test_simple.o] Error 1
```
Similar failures happen for the other integer compares (LessThan, NotEqual, ...) other than Equal.

This is building against pFUnit-4.1.5 with Intel 19.0.4.

**Comment by tclune** [comment]
Ah.   Apparently in 4.0 I started forcing the use of keyword association for some optional arguments.   If you modify the line to be:
```f90
@assertGreaterThan(i_greater, factorial(4), message="greater-int")
```

You should be fine.   For some reason I missed this for the assertEqual() case so your example still works.  Consider that usage deprecated,  v5.0 (in some distant future) will likely more consistently enforce keyword association for optional arguments.

My apologies that this was not discussed in the documentation.
