### ISSUE TITLE
Installing 4.1.7 fails

### ISSUE THREAD

**Issue by reinh-bader** [Goddard-Fortran-Ecosystem/pFUnit#207]
Following README-INSTALL does not appear to work any more, since the GNUMakefiles apparently have been removed. 

The attempt to build with CMake errors out with the complaint that there is no CMakelists.txt in extern/gFTL and other extern subdirs, which indeed are empty (likely also missing other files).

Regards

**Comment by tclune** [comment]
Hmm.   Thought I had removed references to GNUMakefiles in the README.   I'll do another purge after this response.

A likely explanation is that you are using the tar file produced by GitHub.  Unfortunately, GitHub does not capture git submodules when it does that.      With a proper git clone, there are hooks in the CMake to clone the other dependencies, or if you clone with --recursive you get the dependencies included from the get-go.

I'm trying to be good about producing an alternate tar ball each time I release github, but often for quick tweaks I forget.   And checking ... yes underneath the tar file in the release page you should see a tar ball:  [pFUnit.tar](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/releases/download/v4.1.7/pFUnit.tar)

If there is still an issue with the cmake, please let me know.

**Comment by reinh-bader** [comment]
Thanks! With the tarball, cmake builds work fine! The issue can be closed.
