### ISSUE TITLE
Conflicting definitions of m_newpair?

### ISSUE THREAD

**Issue by cferenba** [Goddard-Fortran-Ecosystem/pFUnit#208]
I'm working on compiling pFUnit using the IBM XLF compiler, and it's reporting what may be an error when compiling the file ArgParser.F90:
```
"FArgParser.f90", line 33.8: 1514-699 (S) Procedure "m_newpair" must have a nonoptional dummy argument that corresponds by position in the argument list to a dummy argument not present in procedure "m_newpair", present and type incompatible, present with different kind type parameters, or present with a different rank.
```

Digging into this a bit, I found that `m_newpair` is first defined in file StringActionMap.F90, which after preprocessing contains the following (some intervening lines are omitted):
```fortran
      public :: pair

      interface pair
         module procedure m_newPair
      end interface pair

      function m_newPair(key, value) result(p)
         type (pair) :: p
         character(len=*)  , intent(in) :: key 
         class(BaseAction)  , intent(in) :: value

         p%key=key
         allocate(p%value, source=value)

      end function m_newPair
```

Then `m_newpair` is defined again in StringUnlimitedMap.F90, with a similar set of lines, but using `class(*)` as the type for `value`:
```fortran
      function m_newPair(key, value) result(p)
         type (pair) :: p
         character(len=*)  , intent(in) :: key
         class(*)  , intent(in) :: value

         p%key=key
         allocate(p%value, source=value)

      end function m_newPair
```

Finally, ArgParser.F90 uses the modules from both of the above files:
```fortran
   use fp_StringActionMap
   use gFTL_StringUnlimitedMap
```
This gives (according to XLF) two definitions of `m_newpair` (via the interface `pair`) which conflict with each other (a call with a `value` of type `class(BaseAction)` could be sent to either).

I don't know enough modern Fortran to answer the question:  Is this a real error in the pFUnit coding, which XLF catches even though other compilers let it go by?  Or is the pFUnit coding legal, and XLF has a compiler bug?

Thanks for any help you can give on this...

**Comment by tclune** [comment]
Hmm.  Odd that this did not trip up any of the other compilers.     The fix is fairly trivial.   You could either use the ONLY clause for either/both modules as the Pair derived type is not directly accessed in ArgParse.F90.

But more generally, I would want to override the type name for Pair from the container generator code in gFTL.   E.g., if you look at StringActionMap,  lines 3 and 4 override the container name and the iterator name.   Inserting one more line to override the pair name is the right thing to do.  (I'd long forgotten that I'd even made Pair public - had some use case that required it.)
```f90
#define _pair StringActionPair
```
Untested - but it should work.     

I can implement and test by the weekend, but I'd be more than happy if you could try and do a pull request.

**Comment by cferenba** [comment]
OK, I will give it a try.  Thanks!

**Comment by tclune** [comment]
Actually, I think the code is standard conforming so long as Pair is not actually referenced.

But ... looking again at what you wrote, I now realized I read too quickly.  (Was multitasking.)
Now see that the complaint is about new_Pair().   Those procedures are PRIVATE and do not conflict in any event.  Further, the ONLY clause cannot help with renaming as they are, er, PRIVATE.  This is a bug in the XLF compiler (99% certain).

However, I am happy to put in a small workaround for the XLF compiler, but fixing new_Pair() is a bit trickier than Pair as there is not any existing logic to rename that procedure.   So it will require a patch to gFTL and a new version of pFUnit to reference the newer gFTL.

I'll give this some more thought in the morning.

**Comment by cferenba** [comment]
As I interpreted the error message, the problem was that `m_newpair` in both cases was exposed publicly via the interface `pair`.  If that's the problem, then it's likely that adding `#define pair_` will be enough to make XLF happy.  I'll try that out and see if it's sufficient.

**Comment by cferenba** [comment]
Yes, adding the `#define` for `_pair` as you suggested was enough to fix the XLF issue.  No need to do anything for `m_newpair`.

I'll make a PR for the `_pair` changes in the next couple of days.

**Comment by tclune** [comment]
I'm glad that the minimal approach will resolve the issue and look forward to the PR.

Note, I am still confident that this is an XLF bug, if you feel up to submitting a reproducer to IBM.    PUBLIC for an interface name does not override the default PRIVATE for individual specific names within the interface block.   I suspect that in general that XLF gets this right, but in this case where the name of the interface and the name of the derived type are (intentionally) the same that some corner case was not handled.   I've seen similar problems in other vendors, though not in several years at this point.

**Comment by cferenba** [comment]
At one point in my testing I tried renaming the two `m_newpair` functions to have distinct  names, and the error persisted.  I think the point of the error message was that the `pair` interface had two conflicting definitions, regardless of the underlying specific names.  In principle, there could have been many more specific names in the same interface block, so the error message had to print out specific names to show which ones were conflicting.  So I do think there is a real error that XLF is catching, though perhaps the error message is misleading.

In any case, PR for the fix is coming shortly.

**Comment by tclune** [comment]
@cferenba  I have merged the changes in the two dependencies.   Do you still expect to do a PR on pFUnit itself?      I ask because I'll want to do a PR regardless to update the submodules to point to the latest tags anyway.    But I will wait if a PR for the Pair names is still coming.

**Comment by cferenba** [comment]
@tclune Thanks for the merge!  I'll do a PR for pFUnit shortly.  Haven't quite gotten to it yet.

**Comment by cferenba** [comment]
Resolved by the three PRs listed above.
