### ISSUE TITLE
pfunit.mod isn't built when building with "cmake .. -DSKIP_MPI=YES -DSKIP_FHAMCREST=YES -DSKIP_ESMF=YES"

### ISSUE THREAD

**Issue by kgerheiser** [Goddard-Fortran-Ecosystem/pFUnit#217]
After building with the following CMake command:

`cmake .. -DSKIP_MPI=YES -DSKIP_FHAMCREST=YES -DSKIP_ESMF=YES `

I run `find . -type f -iname "pfunit.mod"` after installing pFUnit and it doesn't exist either as being built or installed.

But if I do a regular build `cmake ..`, `pfunit.mod` is built and installed and my tests work

**Comment by kgerheiser** [comment]
Oh, I get it. `p` is for parllel? and I should just use `funit` if I'm not running in parallel?

**Comment by tclune** [comment]
Yes - though I would phrase it slightly differently.    If the test itself does not involve parallelism, you should use funit.   It is perfectly fine to mix test suites that use funit with those that use pfunit.  But the latter won't work correctly unless the executable is launched with MPI (and of course unless the framework was compiled with MPI support as you discovered.) 

If you know your executables will always involve MPI, then you can always use "pfunit".   I tend to make the distinction in my own tests.   (And it is still a rare day for me when a test really needs MPI support.)
