### ISSUE TITLE
Testing private functions/subroutines

### ISSUE THREAD

**Issue by llamm-de** [Goddard-Fortran-Ecosystem/pFUnit#226]
I have integrated pfUnit into one of my recent projects and it works really fine most of the time. So thanks for developing this tool.

Unfortunately, I was not able to figure out how to test private functions/subroutines of modules/classes.
Hopefully you can give me a hint in the right direction. If it isn't possible at the moment, I would like to suggest to include such a feature in a upcoming release.

Thanks a lot.

**Comment by ChinouneMehdi** [comment]
> I have integrated pfUnit into one of my recent projects and it works really fine most of the time. So thanks for developing this tool.
> 
> Unfortunately, I was not able to figure out how to test private functions/subroutines of modules/classes.
> Hopefully you can give me a hint in the right direction. If it isn't possible at the moment, I would like to suggest to include such a feature in a upcoming release.
> 
> Thanks a lot.

I don't think it's possible to implement that feature.
Private procedures can only be used within the module. There is no way they can be accessed outside of the module.

**Comment by tclune** [comment]
My usual approach when I have something that should be PRIVATE for the API but I still want tested is to introduce an extra module.   Suppose you have a procedure BAR() that is declared PRIVATE in module FOO.     You can then introduce a new module FOO_private and put BAR() in there but declared PUBLIC.    Module FOO then USEs module FOO_private but does not export BAR().   This enables testing while (mostly) not exposing the procedure.

If you are willing to have a dependency on the framework within the source code it is also possible to create a function in FOO that returns a TestSuite object that includes your tests of BAR().        There is currently no mechanism to directly incorporate such a test suite in the drivers provided by the framework,   but it should not be too hard to create a custom driver for this purpose.    And with a bit more thought it might be possible to add an option to the canonical driver to allow for calling a user procedure for test registration.
