### ISSUE TITLE
Incorporating Into An Existing CMake Project

### ISSUE THREAD

**Issue by Michael-A-Heuer** [Goddard-Fortran-Ecosystem/pFUnit#250]
What is the best way to incorporate pFUnit4 into an existing `CMake` project? 
It would be helpful to provide a guide similar to that [available in the googletest repository](https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project), where this can be done via the `ExternalProject_Add()` `CMake` command.

**Comment by tclune** [comment]
The recommended way is :
```find_package(PFUNIT)```
For this to work, pFUnit needs to be installed in a directory seen my `CMAKE_PREFIX_PATH`.

If this approach won't work in your project, then `ExternalProject_Add()` is certainly an option.   I could work with you to add another example in https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos which uses that mechanism on a small demo.

**Comment by rafmudaf** [comment]
I'm working through this in my project, as well. Currently, I'm using `ExternalProject_Add` and I'd also like to use the `add_pfunit_ctest` macro. Maybe I'm misunderstanding, but I think I need to use `find_package` and let CMake know where to find `PFUNITConfig.cmake` in order to get the macro. However, at configure-time, this file does not yet exist.

I'm doing this in a bigger project at the moment but I'll move it to something smaller and share.

**Comment by tclune** [comment]
Thanks - the additional context is helpful.   My original response is that in the  broader scheme of things, using `find_package` is preferable to `ExternalProject_Add`.   I did not mean to imply that you should use _both_.     I agree that a bit more work is likely needed to expose the macros if not using `find_package`.       

I've only used ExternalProject_Add a few times and not in quite some time.    In theory the relevant macro is there in the source directory and it is simply a matter of including that path.      Given that this is CMake, there ought to be "right" way to do this transparently.    I'm happy to make the necessary extensions if someone more experienced with `ExternalProject_Add` can provide guidance on how this ought to work.

**Comment by rafmudaf** [comment]
Is there a reason to not distribute the binaries in some general configuration through a package manager? It would be difficult to capture all use cases and configurations, but I wonder if it would be possible to get most.

**Comment by Michael-A-Heuer** [comment]
With incorporating I meant including it in the project build and not building it separately.  Building it separately and including it with `find_package(PFUNIT)` works fine. Being able to use `ExternalProject_Add` would have the advantage of using the same compiler and linker settings (as mentioned by the googletest) and have it specifically build for one project. Moreover, this makes installation easier for non-experienced users. By the way: thank you for improving pFUnit.

**Comment by tclune** [comment]
@Michael-A-Heuer I am more than happy to take contributions along these lines.   Presumably this would just be a few changes in a few critical spots.

@rafmudaf There is already another user (see #241) that has attempted a Debian distribution.  In that case the current obstacle is the use of the unusual NOSA license.   I hope to eventually fix that, but it will take time.    But more generally, I'm quite open to configuration through a package manager.    This is yet another topic where I am woefully ignorant and would gladly accept contributions to enable such.    Hopefully with some level of commitment for maintaining such capabilities (possibly including in the CI tests?)
