### ISSUE TITLE
'/*' in comment causes error to be generated. 

### ISSUE THREAD

**Issue by kurtsansom** [Goddard-Fortran-Ecosystem/pFUnit#257]
While converting a test to pFUnit the text `/*` in a comment causes compilation to fail. the code that the comment came from builds without error.

Is this a parsing error or something weird with the compiler?

truncated error message
```
  100 |     ! /*
      | 
Error: unterminated comment
```

work arround: Put a space between `/` and `*`

```
OS: Ubuntu 18.04
Compiler: gfortran  GNU Fortran (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0

```

**Comment by tclune** [comment]
Technically it must be a compiler issue, since anything after the `!` is legal.    But I would be curious if you can identify how the change in context caused the compiler to flag it differently.    Maybe there was a matching `*/` in the original code that was not copied over?   (Again should not really matter to Fortran.)

**Comment by kurtsansom** [comment]
I think maybe the difference is that that originating code has a file extension `.f90` and the file extension generated by pFUnit is `.F90` which I think indicates something about the c preprocessor in gcc.  So it does seem clear that it is specific to gfortran and the preprocessor. Is it safe to assume that generating `.F90` files in required for pFUnit versus `.f90`

there is probably a cmake or gcc flag that can force the behavior one way or the other

the difference in the generated code :

```diff
  call assertEqual(2.0_dp/alpha**2, approx, tolerance=tol, &
 & location=SourceLocation( &
 & 'test_class_distribution.pf', &
 & 98) )
  if (anyExceptions()) return
#line 99 "/media/store/krs/itar_build/heat/heat_main/heat/tests/unit_tests/core/utility/test_class_distribution.pf"
    
    ! Compute <x^3> = 6 / alpha^3
+   ! / * compiles not problem
-   ! /* fails to compile
    approx = sum(points(1:Nmax)**3*weights(1:Nmax))
```

**Comment by tclune** [comment]
Ah - that makes sense.    I pretty much universally use `.F90` just in case I ever find the need to use the preprocessor.   E.g., when debugging it is often useful to insert a line:
```f90
print*,__FILE__,__LINE__
```
I'd have to check to be sure I don't ever explicitly use the preprocessor anywhere in the generated code, but if so, I could readily modify add options to toggle the suffix of the generated files.   The default would need to stay `.F90` as I'm sure there are user test suites that use the preprocessor. (Mine included, albeit rarely.)

**Comment by kurtsansom** [comment]
Closing this in favor of a feature request. #259
