### ISSUE TITLE
Can't find 'add_pfunit_ctest' when used as a submodule

### ISSUE THREAD

**Issue by TheoFletcher** [Goddard-Fortran-Ecosystem/pFUnit#287]
With CMake, when I use pFUnit as a submodule and include the directory with `add_subdirectory(pFUnit)` I get the error:

> Unknown CMake command "add_pfunit_ctest".

I think the issue is at the very bottom of the top-level CMakeLists.txt, where `include(add_pfunit_test)` should be `include(add_pfunit_ctest)`. This seemed to fix it for me, but I have very little understanding of the internals of the library to know if this is the correct thing to do or not.

**Comment by tclune** [comment]
Sorry for the delay in responding.  Yes - your analysis is correct.    This logic is relatively recently contributed code, and it only effects embedded builds such as yours.     I'll do a hot fix.   Do you need a formal release, or can you just pull from main for now?

**Comment by TheoFletcher** [comment]
No need for a formal release, thank you very much
