### ISSUE TITLE
Building pFUnit in CMake submodule includes directories from top level

### ISSUE THREAD

**Issue by keyehzy** [Goddard-Fortran-Ecosystem/pFUnit#293]
I'm finding the following problem when trying to include pFUnit as a submodule in a CMake project. 

When I build the project with `ninja -C build/` pFUnit also includes the folders `src/` `tests/` etc. from the the main project directory (top level), and not from its directory and tries to compile the files in it. As a result we compile things in the wrong order and this obviously gives compiling errors.

Is this a known issue and is there is go around this?

This is my minimal example for CMakeLists.txt on the top level

``` cmake
cmake_minimum_required(VERSION 3.12)
project(vacancy Fortran)  
add_subdirectory(vendor)
add_subdirectory(src)
```

CMakeLists.txt inside `vendor/`

``` cmake
cmake_minimum_required(VERSION 3.12)
add_subdirectory(pFUnit)
```

The explicit compiling error is irrelevant imo, but it complains that it can't find modules in the paths. 

```
FAILED: src/CMakeFiles/vacancy.dir/main.f90.o 
/usr/bin/f95 -I../src -g -Jsrc -fpreprocessed -c src/CMakeFiles/vacancy.dir/main.f90-pp.f90 -o src/CMakeFiles/vacancy.dir/main.f90.o
../src/main.f90:10:7:

   10 |   use parameters
      |       1
Fatal Error: Cannot open module file ‘parameters.mod’ for reading at (1): No such file or directory
```

**Comment by tclune** [comment]
I made a trivial example along the lines that you have sketched, but did not encounter any issues.

**Comment by keyehzy** [comment]
I tried to reproduce this in other projects as well but I couldn't, it worked perfectly. This must've been some environment variable that I had setup on there, maybe a newbish mistake but I'm not sure. Thank you and I think it's safe to close this issue.

**Comment by tclune** [comment]
No problem.  Cheers.
