### ISSUE TITLE
long test function names

### ISSUE THREAD

**Issue by kurtsansom** [Goddard-Fortran-Ecosystem/pFUnit#294]
I am refactoring some code from fruit to pfunit and I have a test function name `populate_mappings_with_multiple_key_value_lines` which generates a line that is longer than 132 characters

```fortran
   if(allocated(t)) deallocate(t)
   allocate(t, source=TestMethod('populate_mappings_with_multiple_key_value_lines', populate_mappings_with_multiple_key_value_lines))
   call suite%addTest(t)
```

The solution is to shorten the name of the function, but is there an easier way to deal with this error or maybe change the code generation to use line continuation? I will create a merge request if you can point me where to put it.

also, Identifying the location of the error message is super vague.

```
Error: Line truncated at (1) [-Werror=line-truncation]
/tests/unit_tests/inputs/fortran_yaml_reader_tests/yaml_file_reader_tests.f90:465:132:

Error: Syntax error in ALLOCATE statement at (1)
f951: some warnings being treated as errors
tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/build.make:78: recipe for target 'tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/yaml_file_reader_tests.F90.o' failed
make[2]: *** [tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/yaml_file_reader_tests.F90.o] Error 1
CMakeFiles/Makefile2:3247: recipe for target 'tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/all' failed
make[1]: *** [tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

Thank you for your time.

**Comment by kurtsansom** [comment]
I think I identified where I can modify things.

https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/bc4de1fa39f1eb8843cb60e2f418787301dde06e/bin/funit/pFUnitParser.py#L828-L829

**Comment by kurtsansom** [comment]
I guess another way to resolve this is to use the `-ffree-line-length-n` compiler flag. e.g. `-ffree-line-length-512`

**Comment by tclune** [comment]
Yes- feel free to submit a PR to split the line/source bit in the preprocessor.      (Pending the CLA ...)

**Comment by tclune** [comment]
And yes, the reason the line restriction has not bothered me is because I've just grown used to applying compiler specific flags that allow long lines.     The main model I work on uses macros to trap errors, and these are quite often longer than 132 characters.
