### ISSUE TITLE
Bug in CMake: use of `BUILD_SHARED` instead of `BUILD_SHARED_LIBS`

### ISSUE THREAD

**Issue by ZedThree** [Goddard-Fortran-Ecosystem/pFUnit#304]
There's a few uses of `BUILD_SHARED` in the CMake files that should be `BUILD_SHARED_LIBS`. This can lead to an issue where the `pfunit_shared` target isn't defined, for instance.

Looks like the only instances are these:

```
$ find . -type f | xargs grep -nE "\bBUILD_SHARED\b"
./cmake/PFUNITConfig.cmake.in:58:set (PFUNIT_BUILD_SHARED "@BUILD_SHARED@")
./tests/CMakeLists.txt:3:set (PFUNIT_BUILD_SHARED ${BUILD_SHARED})
./src/efunit/CMakeLists.txt:20:if (BUILD_SHARED)
./src/funit/CMakeLists.txt:69:if (BUILD_SHARED)
./src/pfunit/CMakeLists.txt:4:if (BUILD_SHARED)
```

Fix is:

```
for f in $(find . -type f | xargs grep -lE "\bBUILD_SHARED\b"); do sed -i 's/\bBUILD_SHARED\b/BUILD_SHARED_LIBS/' $f; done
```

I'm very happy to submit a PR, I'm just not sure what the situation is with the CLAs!

**Comment by tclune** [comment]
@ZedThree - sorry for the delay in responding.   Back for a few days between 2 (post vaccine) vacations to visit family.  

Lawyer had actually signed off on your CLAs' just before I left, and I'm now beating myself up for not reading your message earlier this week.   

Please do the PR.   I may not be able to review/merge until next week though.
