### ISSUE TITLE
OTHER_SOURCES Makefile variable

### ISSUE THREAD

**Issue by tkoskela** [Goddard-Fortran-Ecosystem/pFUnit#311]
There are multiple references to a `OTHER_SOURCES` Makefile variable that does not seem to get used anywhere. For example

https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/main/README.md#using-pfunit-in-a-gnu-make-project

and in the demos

https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos/blob/eae49e1f7a0e2ba002f1c5dfbeceb3c51026b878/Trivial/Makefile#L29

The variable that is used in `PFUNIT.mk` is `OTHER_SRCS`, which I think these should refer to.

**Comment by tclune** [comment]
Thank you for catching this.    I'm torn between fixing the documentation and changing the GNU make to be consistent with the CMake macro which uses the unabbreviated form.        The latter is preferred, but ... I don't want to break things for anyone that is using the abbreviation.     I suppose I could make the GNU make use both and then the legacy uses will be fine and the documentation will steer new users to the preferred spelling.

Does that sound ok?

**Comment by tkoskela** [comment]
I am ok with either way, but I do agree that not breaking things for legacy users is preferable.
