### ISSUE TITLE
pFUnit build with openMPI, but mpi-tests all fail

### ISSUE THREAD

**Issue by micric** [Goddard-Fortran-Ecosystem/pFUnit#322]
I built pFUnit using Intel Fortran 2019 and openmpi 4.1.0, following the instructions on the main page Everything works fine, until I run make tests.
All MPI tests fail with an error like

Failure
 in:
Test_MpiParameterizedTestCase.testRunOn2PEs[npes=2 :: 1][npes=2 :: 1]
  Location:
[unknown location]
Insufficient processes to run this test. (PE=0)

I tested MPI on simple programs and they can run multiprocess.
Any clue on what the problem might be?

**Comment by tclune** [comment]
Hmm.  That is odd.   Usually this happens with projects that _use_ pfunit and unintentionally launch parallel tests without invoking MPI.     But the pfunit self tests certainly invoke MPI if MPI is found (and the parallel tests would not be run at all without that).

My only immediate thought is that there are two different MPIs on the system and somehow the tests are launched with one and the build is linking with the other.   Not likely the explanation, but it is the only thing that I can think of at the moment.

Could you try a fresh cmake step and post here the output of what is reported?  Maybe something in that will suggest a different issue?

**Comment by micric** [comment]
That was my first idea as well, since on the system it could find both openMPI and IntelMPI. I tried rebuilding everything, making sure  that it was pointing to openMPI all the time (or trying to, I could still have made something wrong...). It still fails.
I will try a fresh cmake as you suggested and post the output here. Thanks for your help

**Comment by micric** [comment]
This is the output of CMake @tclune 

-- The Fortran compiler identification is Intel 19.0.0.20190117
-- The C compiler identification is GNU 8.3.0
-- Check for working Fortran compiler: /opt/intel/compilers_and_libraries_2019.2.187/linux/bin/intel64/ifort
-- Check for working Fortran compiler: /opt/intel/compilers_and_libraries_2019.2.187/linux/bin/intel64/ifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/intel/compilers_and_libraries_2019.2.187/linux/bin/intel64/ifort supports Fortran 90
-- Checking whether /opt/intel/compilers_and_libraries_2019.2.187/linux/bin/intel64/ifort supports Fortran 90 -- yes
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- *** Setting default install prefix to /home/pFUnit/build/installed.
-- *** Override with -DCMAKE_INSTALL_PREFIX=<path>.
-- Setting build type to 'Debug' as none was specified.
-- Performing Test _LOGICAL_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _INT_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _ISO_INT8: SUCCESS (value=1)
-- Performing Test _ISO_INT16: SUCCESS (value=2)
-- Performing Test _ISO_INT32: SUCCESS (value=4)
-- Performing Test _ISO_INT64: SUCCESS (value=8)
-- Performing Test _REAL_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _DOUBLE_DEFAULT_KIND: SUCCESS (value=8)
-- Performing Test _ISO_REAL32: SUCCESS (value=4)
-- Performing Test _REAL32_IEEE_SUPPORT: SUCCESS (value=T)
-- Performing Test _ISO_REAL64: SUCCESS (value=8)
-- Performing Test _REAL64_IEEE_SUPPORT: SUCCESS (value=T)
-- Performing Test _ISO_REAL128: SUCCESS (value=16)
-- Performing Test _REAL128_IEEE_SUPPORT: SUCCESS (value=T)
-- MPI enabled
-- OpenMP enabled
-- Found Python: /usr/bin/python3.7 (found version "3.7.3") found components:  Interpreter
-- Using submodule /home/pFUnit/extern/fArgParse
-- Using submodule /home/pFUnit/extern/fArgParse/extern/gFTL-shared
-- Performing Test _LOGICAL_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _INT_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _ISO_INT8: SUCCESS (value=1)
-- Performing Test _ISO_INT16: SUCCESS (value=2)
-- Performing Test _ISO_INT32: SUCCESS (value=4)
-- Performing Test _ISO_INT64: SUCCESS (value=8)
-- Performing Test _REAL_DEFAULT_KIND: SUCCESS (value=4)
-- Performing Test _DOUBLE_DEFAULT_KIND: SUCCESS (value=8)
-- Performing Test _ISO_REAL32: SUCCESS (value=4)
-- Performing Test _ISO_REAL64: SUCCESS (value=8)
-- Performing Test _ISO_REAL128: SUCCESS (value=16)
-- Using submodule /home/pFUnit/extern/fArgParse/extern/gFTL-shared/extern/gFTL
-- Setting default install prefix to /home/pFUnit/build/installed.
   Override with -DCMAKE_INSTALL_PREFIX=<path>.
-- Using target 'FARGPARSE::fargparse'
-- Using target 'FARGPARSE::fargparse'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pFUnit/build

**Comment by tclune** [comment]
Hmm. `FindMPI` is apparently not as verbose as one might hope here.   So ... the next step is to do a verbose build:
```
make tests VERBOSE=1
```
That should show us the full path of everything such that we can see which mpi is being invoked and linked.   We can then separately explicitly launch the parallel tests with
```
which mpirun
mpirun -np 8 ./tests/pfunit/parallel_tests.x
mpirun -np 8 ./tests/pfunit/new_ptests.x
```

**Comment by micric** [comment]
Finally found the issue. It was a combination of things. At first, there was the problem of having Intel MPI found first in PATH. I had fixed that, but I hadn't set the two environment variables to run openMPI as root:
OMPI_ALLOW_RUN_AS_ROOT=1
OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
Since I'm running this in a Docker container, I was also running as root.

@tclune  Thanks for your help, sorry to have opened an issue for something that it was not really related to pfUnit in the end.
I hope this might help others trying to build a docker image with pfUnit anyway.

**Comment by tclune** [comment]
No problem.  Glad you resolved the issue.
