### ISSUE TITLE
MPI test compiling/linking issues

### ISSUE THREAD

**Issue by SMijin** [Goddard-Fortran-Ecosystem/pFUnit#323]
Hello,

I've been trying to get an MPI test suite running, and have not been able to compile my test at all. I have rebuilt pFUnit a few times using different installation directories, but the issues remain. I'm trying to build using cmake, so I'm attaching a working minimal test and an mpi test that fails to compile, alongside the cmake file. The compiler used for everything is the latest oneapi ifort version.

[CMakeLists.txt](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/files/6901728/CMakeLists.txt)

Working test:
```
@test
`subroutine working
  use pfunit
  implicit none
  @assertTrue(.false.)
end subroutine working
```

Test failing to compile:

```
@test(npes=[2])
subroutine failing(this)
    use pfunit
    implicit none
    
    class(MpiTestMethod) ,intent(inout) :: this

    @assertTrue(.false.)
   
end subroutine failing
```
Trying to compile the above produces the following error: 
```
error #6404: This name does not have a type, and must have an explicit type.   [MPITESTMETHOD]
   allocate(t, source=MpiTestMethod('failing', &
----------------------^
```

Changing the failing subroutine to be contained in a module:
```
module testing1 
use pfunit
implicit none

contains
@test(npes=[2])
subroutine failing(this)
    
    class(MpiTestMethod) ,intent(inout) :: this

    @assertTrue(.false.)
   
end subroutine failing
end module
```
produces the following linker error:
```
ld: CMakeFiles/failing.dir/failing.F90.o: in function `testing1_suite_':
failing.F90:(.text+0x9b7): undefined reference to `pf_mpitestmethod_mp_newmpitest_basic_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa00): undefined reference to `pf_mpitestcase_mp_counttestcases_mpi_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa08): undefined reference to `pf_mpitestcase_mp_run_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa38): undefined reference to `pf_mpitestcase_mp_runbare_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa40): undefined reference to `pf_mpitestmethod_mp_setup_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa48): undefined reference to `pf_mpitestmethod_mp_teardown_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa58): undefined reference to `pf_mpitestmethod_mp_runmethod_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa68): undefined reference to `pf_mpitestcase_mp_getnumprocesses_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa70): undefined reference to `pf_mpitestcase_mp_getnumprocessesrequested_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa78): undefined reference to `pf_mpitestcase_mp_getprocessrank_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa80): undefined reference to `pf_mpitestcase_mp_getmpicommunicator_'
ld: CMakeFiles/failing.dir/failing.F90.o:(.rodata+0xa88): undefined reference to `pf_mpitestcase_mp_getcontext_'
ld: CMakeFiles/failing.dir/failing_driver.F90.o: in function `loader_mp_load_tests_':
failing_driver.F90:(.text+0x878): undefined reference to `failing_suite_'
make[2]: *** [CMakeFiles/failing.dir/build.make:131: failing] Error 1
make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/failing.dir/all] Error 2
make: *** [Makefile:114: all] Error 2
```
I have tried to find someone with similar issues, but couldn't (not ruling out that I didn't look hard enough). These errors look like I'm missing something pretty trivial, but I've checked the installation directory of pFUnit, made sure that both the library and the sut are compiled using the same compiler, but the errors persist. Weirdly only for the MPI tests. 

Thank you for your patience!
Stefan

**Comment by tclune** [comment]
Sorry for the long hiatus - have been a bit preoccupied with other things of late, and keep meaning to deal with pFUnit issues on the weekends.   And then somehow manage to not actually touch the computer on the weekend.


Ah - I think I see the problem.    You did not specify `MAX_PES` as an argument to the `add_pfunit_ctest` macro.   The macro uses this to determine that you need `pfunit` and not just `funit` and is therefore not bringing in the correct libraries and include paths.    Please let me know.

**Comment by tclune** [comment]
@SMijin and @micric   did my suggestion of using MAX_PES resolve your issue?

**Comment by SMijin** [comment]
@tclune, @micric  I'm afraid I've not been able to check this as I'm taking a break from that particular Fortran project (and have changed my development setup in the meantime). I'll bookmark this issue for when I return to Fortran development. Sorry for not having any feedback for you at this point.

**Comment by SMijin** [comment]
@tclune  Just got back to this, and adding MAX_PES does not solve the problem. The error in the first case is the same, while only the following error happens in the case when the test is nested in a module:

```
ld: CMakeFiles/failing.dir/failing_driver.F90.o: in function `loader_mp_load_tests_':
failing_driver.F90:(.text+0x878): undefined reference to `failing_suite_'
```
The solution mentioned by @micric does not seem work for me.

**Comment by tclune** [comment]
Sorry for the delay in responding.     The module naming issue is unrelated and was mentioned recently in another issue (#327).   It is summarized in more detail there, but basically the preprocessor has to make certain assumptions about the  test suite name from just the file name.   When the module name does not align with those expectations one must explicitly tell the preprocessor what suite name to use.  E.g.,
```
@suite(name='test_projectile_motion_suite')
```

**Comment by SMijin** [comment]
Thanks! Everything works now with MPI tests wrapped in modules. I've not tried standalone MPI tests again (outside a module), but I don't think of that as a necessary feature - I find that organizing tests in modules makes for cleaner code.
