### ISSUE TITLE
@assertNotEqual not working for integers

### ISSUE THREAD

**Issue by danielhollas** [Goddard-Fortran-Ecosystem/pFUnit#353]
It looks like `@assertNotEqual` is not overloaded for integers?

```fortran
integer :: int1=1, int2=2
@assertNotEqual(int1,int2, "test") 
```
```sh
$ Error: There is no specific subroutine for the generic 'assertnotequal'
```
Including the message keyword fixes the compilation, but the test does not work as expected
```fortran
integer :: int1=1, int2=2
@assertNotEqual(int1, int2, "test") 
```
```sh
AssertNotEqual failure:
    Same value: <34>
```
Converting integers to reals works
```fortran
integer :: int1=1, int2=2
@assertNotEqual(real(int1), real(int2), "test") 
```

What am I missing? (tested with GCC-7, will test higher versions if needed)

**Comment by tclune** [comment]
This is bizarre.  Lot's of tests compare integers.

**Comment by danielhollas** [comment]
Ah, sorry, in my examples I wanted to have `assertNotEqual`. Could you try it? Thanks for quick response! :heart:

**Comment by danielhollas** [comment]
@tclune I've just added your simple test case with `assertNotEqual` into my test suite and the build fail for all GCC versions that I am testing - 7, 9, 10, on Ubuntu image 18.10.

See for example
https://github.com/PHOTOX/ABIN/runs/6096737798?check_suite_focus=true

**Comment by tclune** [comment]
Your other option in the mean time is simply to do:
```
assertTrue(int1 /= int2, message=...)
```
Failure messages will be less useful though.

**Comment by tclune** [comment]
The bug was easier to spot than I feared.  (The overloads are done by a python preprocessor, which makes the source code for assertions a bit opaque.)

Hot fix is in with the CI now.  If it finishes soon, I'll roll out 4.3.0 before I head home.
