### ISSUE TITLE
Clarify status of documentation and examples

### ISSUE THREAD

**Issue by tlestang** [Goddard-Fortran-Ecosystem/pFUnit#361]
It is unclear to me what is the best way to learn about the features available in pFUnit, and how to use them.
In terms of available documentation, I can list

- the documentation/ folder (declared out of date)
- the Examples/ folder (declared out of date)
- the pFUnit_demos repos, declared as the current source of truth.

Having the demos is really useful, but do they describe the entirety of what is possible with the framework? If no, are there any other ressources available - for instance looking for a description of the available `@assert` decorators?

**Comment by tclune** [comment]
Yeah - documentation is not my strong suit.      The demos were meant to grow to be more exhaustive, but that has not happened.

For the older style assertions  `@assertEqual()` and such, you can look in the source and see the various interfaces at the top of the files in `./src/funit/asserts`.  Must should be suggestive.       You can also infer a fair bit from this snippet of python in the parser:   https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/26ac761630dd3012081d67ce03ee99bff2dbe8d9/bin/funit/pFUnitParser.py#L18-L24
This is possibly incomplete, but if so, not by much.

Then for the newer style "hamcrest"  `@assert_that()` style, it is more about composing things.  The "matchers" are all in `./src/funit/fhamcrest`,  but some of the files there are infrastructure.   It might be useful for me to create a subdirectory with the individual options.

And of course, I can usually respond fairly quickly with easy questions.   So if you have a few types of assertions that you'd like to make I can quickly rattle off how to do them (or tell you that pfunit lacks such features).

**Comment by tlestang** [comment]
Thank you for the quick reply. I'll have a look at the parser then.

> Yeah - documentation is not my strong suit.

Looks like you are maintaining/developing the framework mostly your own. I appreciate this must be a lot of work and there must always be something else to do rather than writing docs! I'm working on a unit test suite for a Fortran CFD framework ([xcompact3d](https://www.incompact3d.com/)). This might take a while but hopefully we can contribute back examples and documentation for the feature of pFUnit we end up using.

**Comment by tclune** [comment]
Yes - mostly on my own.  OTOH it's pretty stable these days.   And while I frequently use pFUnit in my other work, it already does what _I_ need, and I (usually) know what it can and can't already do.

There have been other documentation efforts.    There have been 2 major efforts.  The first was when I had some funding, but it is now very obsolete.  The other was with a private company that was developing documentation for a customer and chose not to contribute the documentation to the repo.    Unfortunate, but I understand their reasoning.
