### ISSUE TITLE
Using MAX_PES as a variable for NPES

### ISSUE THREAD

**Issue by nasa-ceporter** [Goddard-Fortran-Ecosystem/pFUnit#375]
Currently my unit tests have hard coded values of `npes` to test a single process and an arbitrary case with 4 processes.

```fortran
   @test(npes=[1, 4])
   subroutine foo(this)
       integer :: bar
   end subroutine foo
```

Is there a way to touch MAX_PES somehow such that I can do something like this?

```fortran
   @test(npes=[1, MAX_PES])
   subroutine foo(this)
       integer :: bar
   end subroutine foo
```

**Comment by tclune** [comment]
There is a kludge for this.  If you specify a value of `0` it will attempt to use the number of processes in the "parent context".  This will be the number of processes in `MPI_COMM_WORLD` unless you have done something particularly unusual.
@test(npes=[1, 0])
   subroutine foo(this)
       integer :: bar
   end subroutine foo

**Comment by nasa-ceporter** [comment]
That works for me! Thanks Tom. We in the `GlennICE` team at NASA GRC love the work here.
