### ISSUE TITLE
Feature Request: Misnamed Test Module Diagnostic

### ISSUE THREAD

**Issue by jphill4** [Goddard-Fortran-Ecosystem/pFUnit#379]
I was migrating an existing test harness to pFUnit and had a hard time diagnosing a build failure in doing so. I had test file "hello_test.pf", but it defined module "test_hello" (hold over from previous implementation), which caused the build to fail with non-helpful error messages. Since pFUnit expects module name to match file name, it would be nice to have some kind of check/diagnostic in the pre-processor to verify this is in fact the case.

**Comment by tclune** [comment]
My apologies - busy week.    I hope to catch up on this issue (and the others you submitted) over the weekend.  At first glance the requests seem reasonably straightforward to accommodate.

**Comment by jphill4** [comment]
No rush. Mostly just wanted to capture the issues for future releases. I can even potentially submit some PRs towards the end of the year as things slow down (I'm NASA, so familiar with the CLA).

**Comment by tclune** [comment]
Thank you for requesting this feature -- I myself often stumble over this when I've been away from the framework for a while.  Also, note that there is a `@suite(name=...)` semaphore to override.      

I've implemented a patch that will raise an exception when the module and filename disagree (except if `@suite` has been used).
