### ISSUE TITLE
How to run just one test?

### ISSUE THREAD

**Issue by citibeth** [Goddard-Fortran-Ecosystem/pFUnit#38]
Is it possible to run just a single tests (or one of a few tests) out of a full suite?  By running the executable and searching for command line options, I don't see any way:

```
 Command line arguments:
  
  Options: 
    '-h', '--help'    : Prints this message
    '-v', '--verbose' : Logs start/stop of each test
    '-d', '--debug'   : Logs start/stop of each test (same as -v)
    '-o <file>'       : Diverts output to specified file
    '-robust'         : (experimental) runs tests in a separate shell
                        Attempts to detect/handle hangs and crashes
    '-max-timeout-duration <duration>' : Limit detection time for robust
    '-max-launch-duration  <duration>' : Limit detection time for robust
    '-skip n'         : used by remote start with 'robust' internally
                        This flag should NOT be used directly by users.
    '-xml <file>'     : output JUnit XML to specified file
                        XML can be used with e.g. Jenkins.
    '-name <name>'    : give tests an identifying name in XML output
```

**Comment by tclune** [comment]
No - there is not a good way to do this with the current pFUnit.    One of the goals of 4.0 is to significantly improve the flexibility in running subsets of tests in various respects.      

The primitive bit that is already in the development branch is to specify a separate testSuites.inc file.    This would let you have an executable that runs just one test suite, which is still a bit coarse grained.   

If you have suggestions on what would be the most convenient way for the user to specify the test(s) that they want to run, I'm certainly receptive.      "grep" is not fun to write in Fortran, and as you know, I'm wary of introducing additional software dependencies.     

In practice, I'm usually content with just commenting out all but one line in the testSuites.inc file.   In rare cases I may go in and comment out most of the @test's in the remaining suite.    Usually these are just debugging exercises and then I reactivate everything when things are patched.   Klunky, but hopefully not something you need to do frequently.

**Comment by tclune** [comment]
@citibeth    Some fruits of only being allowed to work on open source stuff during the furlough.   

```
./tests/core-tests/new_tests.x -h
 usage: ./tests/core-tests/new_tests.x [-h][-d][-f FILTER]
  
 optional arguments:
  -h, --help                 This message.
  -d, --debug, --verbose     make output more verbose
  -f, --filter               only run tests that match FILTER
bash-3.2$ ./tests/core-tests/new_tests.x
................................................................................
................................................................................
............I.....................
Time:         0.008 seconds
  
 OK
 (193 tests, 1 disabled)
bash-3.2$ ./tests/core-tests/new_tests.x -f multi
.
Time:         0.000 seconds
  
 OK
 (1 test)
```

Note that this is only on the develop branch and won't be pushed to master until the rest of 4.0 is ready for release.

**Comment by tclune** [comment]
Also - still needs some comparable changes for the MPI case.    Need to find a way to refactor so that the options are only defined in one place.
