### ISSUE TITLE
Typo in release v4.7.4

### ISSUE THREAD

**Issue by foeroyingur** [Goddard-Fortran-Ecosystem/pFUnit#443]
There is a typo in CMakeLists.txt in the v4.7.4 release:
```
project (PFUNIT
  VERSION 4.7.3
  4
  LANGUAGES Fortran C)
```

**Comment by tclune** [comment]
Hmm. This error was fixed almost immediately after I made it.  But I apparently forgot to re-release ... On it.

**Comment by tclune** [comment]
OK - hopefully all is good now.  (I try not to reuse tags, but ... am in a rush.)
