### ISSUE TITLE
Remove outdated documentation

### ISSUE THREAD

**Issue by MatthewHambley** [Goddard-Fortran-Ecosystem/pFUnit#450]
There seems to be documentation in the repository left over from v3 and possible even v2 and v1. I think this is getting to the point of "outdated documentation is worse than no documentation." This seems particularly relevant to the examples directory which may not match v3 usage let alone v4.

I understand that there is little time to improve the documentation but deleting that which is so old as to be completely misleading should be manageable.

**Comment by tclune** [comment]
Fair point.  I will delete the pdf file on my next PR.
