### ISSUE TITLE
Missing implementation of assertIsFinite_real80 in src/funit/asserts/AssertBasic.F90 

### ISSUE THREAD

**Issue by sscalpone** [Goddard-Fortran-Ecosystem/pFUnit#452]
Flang isn't finding an implementation of assertIsFinite_real80.   Is it missing from AssertBasic.F90?

**Comment by sscalpone** [comment]
Will do!

**Comment by tclune** [comment]
I'm excited that Flang may finally be at the point where it can compile this GFE layer.    If so, I will make the investments to get the rest of my software stack ported.

**Comment by mathomp4** [comment]
@sscalpone A query: where did you get flang? I tried long ago to build from LLVM source and gave up after the build reached 8 hours.

**Comment by sscalpone** [comment]
@mathomp4  I build from LLVM top-of-tree without debugging.   The memory requirement to compile flang has been reduced over the past year, so it's more reasonable now.  There's a slack channel if you want to ask questions.

@tclune We're pretty excited to be closing in on pFUnit and pFlogger!  There are some patches in flight that won't land until the middle of next week that are needed.

**Comment by mathomp4** [comment]
> @mathomp4 I build from LLVM top-of-tree without debugging. The memory requirement to compile flang has been reduced over the past year, so it's more reasonable now. There's a slack channel if you want to ask questions.

@sscalpone I might take you up on that. I did just try and got...close with 18.0.2-rc2:

```
********************
Failed Tests (7):
  Flang :: HLFIR/forall-index.fir
  Flang :: Lower/HLFIR/forall.f90
  Flang :: Lower/OpenMP/FIR/wsloop-reduction-logical-and.f90
  Flang :: Lower/OpenMP/FIR/wsloop-reduction-logical-eqv.f90
  Flang :: Lower/OpenMP/FIR/wsloop-reduction-logical-neqv.f90
  Flang :: Lower/OpenMP/FIR/wsloop-reduction-logical-or.f90
  flang-Unit :: Runtime/./FlangRuntimeTests/NoArgv/FdateNotSupported


Testing Time: 40.89s

Total Discovered Tests: 2767
  Unsupported      :   80 (2.89%)
  Passed           : 2665 (96.31%)
  Expectedly Failed:   15 (0.54%)
  Failed           :    7 (0.25%)
```
