### ISSUE TITLE
imp is deprecated

### ISSUE THREAD

**Issue by sanguinariojoe** [Goddard-Fortran-Ecosystem/pFUnit#469]
[Here](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/a192e82246b44e701446811a9792a530e4f250c7/source/GenerateAssertsOnArrays.py#L36) you are using imp, which is not anymore a module on Python 3.12+

Also that logic is quite convoluted. I would rather do

```
try:
    import argparse
except ImportError:
    print('GenerateAssertOnArrays.py::Error. pFUnit requires argparse module provided by python version >= 2.7.')
    print('Quitting!'); quit()
```

**Comment by tclune** [comment]
OK.   Will be happy to merge a PR if you can do that.   Might be some time before I get to it otherwise.  Lots of travel in June, so am only able to spend limited time on my sideline open source projects.

Cheers.

**Comment by sanguinariojoe** [comment]
Something really weird and odd is happening... The code I was pointing was coming from OpenFAST, but apparently they are using a REALLY OLD version of pFUnit.

On the current version there is nothing like this anymore. Sorry for bothering!
