### ISSUE TITLE
regression tests broken in travis?

### ISSUE THREAD

**Issue by tclune** [Goddard-Fortran-Ecosystem/pFUnit#68]
@mathomp4   I'm a bit confused why the latest regression tests for merge requests onto develop are breaking.   My own test for gfortran+OSX with a fresh clone works just fine.

My best bet is that I've introduced a new dependency with some of my C interoperability updates.   Could use your help in fixing.

**Comment by tclune** [comment]
Actually, it is failing far before any of those sorts of issues.   It is failing where it should be attempting to build the fArgParse submodule, but does not even mention that.  Simply finishes the gFTL-shared dependency and then complains that it can't find an executable it was supposed to build inside pFUnit proper.   Very weird.     Perhaps I've messed up something in the fArgParse integration.   But again - works just fine from scratch on my home mac mini.

**Comment by tclune** [comment]
OK - I've reproduced the issue on my laptop.    So either it is the OS level (mac mini is at mojave, but laptop is high sierra), or it is something with homebrew of gfortran vs spack gfortran.

**Comment by mathomp4** [comment]
Huh. That is weird. 

Does the failure of `posix_predefined.inc` trigger the gFTL-shared build?

**Comment by tclune** [comment]
Hmm.  Did I miss an earlier message in the log?   I'd not seen anything about posix_predefined.inc there.   Certainly it is a newer change and could be part of the cause.

**Comment by mathomp4** [comment]
Well, develop seems to build now. Maybe I was looking at the wrong test on Travis?

**Comment by mathomp4** [comment]
Oh. wait here it is:

```
[  4%] Linking C executable posix_predefined.x
-- Generating done
-- Build files have been written to: /home/travis/build/Goddard-Fortran-Ecosystem/pFUnit/build/gFTL/src/gFTL-build
[  4%] Built target posix_predefined.x
[  4%] Performing build step for 'gFTL'
Scanning dependencies of target generate_posix_parameters
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[  5%] posix_predefined.inc
make[2]: *** [src/core/posix_predefined.inc] Error 45
make[2]: *** Deleting file `src/core/posix_predefined.inc'
make[1]: *** [src/core/CMakeFiles/generate_posix_parameters.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
