### ISSUE TITLE
bin/__pycache__/ files not ignored

### ISSUE THREAD

**Issue by JonasToth** [Goddard-Fortran-Ecosystem/pFUnit#71]
Dear pFUnit-team,

we use pFUnit in our internal project (and its great!) but have an issue, that the python installation creates
`bin/__pycache__/foo.pyc` files that are not ignored with the `.gitignore` in `bin/`. As we have pFUnit as git-submodule it is a small annoyance that it is dirty all the time :/

Changing the `bin/.gitignore` from `/*.pyc` to `*.pyc` (as in `source/`) would fix that issue.

Thank you very much!

**Comment by tclune** [comment]
@JonasToth  I'm happy to make the change.   Not using submodules, I'd not ever noticed this.

Might not get to it until this evening.

**Comment by JonasToth** [comment]
Thank you very much! There is not pressure :)
